# Netlify build settings
[build]
  command = "npm install && npm install @vitejs/plugin-react && npm run build"
  publish = "dist"
  environment = { VITE_SUPABASE_URL = "${VITE_SUPABASE_URL}", VITE_SUPABASE_ANON_KEY = "${VITE_SUPABASE_ANON_KEY}" }

# SPA redirect rule
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200