// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zxqklbuxeyomxczxtsvp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp4cWtsYnV4ZXlvbXhjenh0c3ZwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4MjEzMDksImV4cCI6MjA1OTM5NzMwOX0.uiXfQAYYBXUXGOIQpzb4ZyWRKjqUyBB5TJSRFEisnAE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);